[project]
name = "object-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.0.3",
    "flask-cors>=6.0.1",
    "langchain-ollama>=1.0.0",
    "numpy > 1.22.3",
    "pillow>=12.0.0",
    "scipy>=1.16.3",
    "supabase>=2.24.0",
    "torch>=2.9.1",
    "transformers>=4.57.1",
]
